version: '3'

services:
  api:
    command: npm run dev
    volumes:
      - ./server:/api
      
  client:
    command: npm run start
    stdin_open: true
    tty: true
    volumes:
      - ./client/src:/client/src